Subject: Hello via HTML
From: chris.p.clark@gmail.com
To: chris.p.clark@gmail.com
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="===============4086234364361572120=="

--===============4086234364361572120==
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit

Salut!

Cela ressemble  un excellent recipie[1] djeuner.

[1] http://www.yummly.com/recipe/Roasted-Asparagus-Epicurious-203718

--Pep

--===============4086234364361572120==
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: 7bit
MIME-Version: 1.0

<html>
  <head></head>
  <body>
    <p>Salut!</p>
    <p>Cela ressemble  un excellent
        <a href="http://www.yummly.com/recipe/Roasted-Asparagus-Epicurious-203718">
            recipie
        </a> djeuner.
    </p>
    <img src="cid:156034474011.16412.8514085390759878058@chrissy-Inspiron-5680" />
  </body>
</html>

--===============4086234364361572120==--
