# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1282, 917)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit_Log = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_Log.setGeometry(QtCore.QRect(20, 210, 1241, 111))
        self.textEdit_Log.setReadOnly(True)
        self.textEdit_Log.setObjectName("textEdit_Log")
        self.pushButton_Start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Start.setGeometry(QtCore.QRect(0, 840, 80, 22))
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.pushButton_Quit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Quit.setGeometry(QtCore.QRect(1020, 840, 80, 22))
        self.pushButton_Quit.setObjectName("pushButton_Quit")
        self.labelTime = QtWidgets.QLabel(self.centralwidget)
        self.labelTime.setGeometry(QtCore.QRect(90, 0, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelTime.setFont(font)
        self.labelTime.setObjectName("labelTime")
        self.lcdNumberDirectionDeg = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumberDirectionDeg.setGeometry(QtCore.QRect(1140, 430, 81, 21))
        self.lcdNumberDirectionDeg.setObjectName("lcdNumberDirectionDeg")
        self.labelDirectionDeg = QtWidgets.QLabel(self.centralwidget)
        self.labelDirectionDeg.setGeometry(QtCore.QRect(1030, 420, 61, 51))
        self.labelDirectionDeg.setObjectName("labelDirectionDeg")
        self.labelDirectionStr_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelDirectionStr_2.setGeometry(QtCore.QRect(1020, 380, 71, 51))
        self.labelDirectionStr_2.setObjectName("labelDirectionStr_2")
        self.labelDirectionStr = QtWidgets.QLabel(self.centralwidget)
        self.labelDirectionStr.setGeometry(QtCore.QRect(1140, 400, 121, 21))
        self.labelDirectionStr.setObjectName("labelDirectionStr")
        self.lcdNumberCounter = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumberCounter.setGeometry(QtCore.QRect(280, 790, 141, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lcdNumberCounter.setPalette(palette)
        self.lcdNumberCounter.setObjectName("lcdNumberCounter")
        self.lcdNumberTotalMessageCount = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumberTotalMessageCount.setGeometry(QtCore.QRect(450, 790, 131, 51))
        self.lcdNumberTotalMessageCount.setObjectName("lcdNumberTotalMessageCount")
        self.labelMessageCounter = QtWidgets.QLabel(self.centralwidget)
        self.labelMessageCounter.setGeometry(QtCore.QRect(280, 720, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelMessageCounter.setFont(font)
        self.labelMessageCounter.setObjectName("labelMessageCounter")
        self.labelCompass = QtWidgets.QLabel(self.centralwidget)
        self.labelCompass.setGeometry(QtCore.QRect(1030, 470, 231, 231))
        self.labelCompass.setFrameShape(QtWidgets.QFrame.Box)
        self.labelCompass.setText("")
        self.labelCompass.setObjectName("labelCompass")
        self.labelGust_4 = QtWidgets.QLabel(self.centralwidget)
        self.labelGust_4.setGeometry(QtCore.QRect(68, 1087, 119, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelGust_4.setFont(font)
        self.labelGust_4.setObjectName("labelGust_4")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 60, 1241, 134))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lcdNumberRain = QtWidgets.QLCDNumber(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lcdNumberRain.setFont(font)
        self.lcdNumberRain.setObjectName("lcdNumberRain")
        self.gridLayout_2.addWidget(self.lcdNumberRain, 3, 1, 1, 1)
        self.labelRain = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelRain.setFont(font)
        self.labelRain.setObjectName("labelRain")
        self.gridLayout_2.addWidget(self.labelRain, 3, 0, 1, 1)
        self.labelTemperature = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelTemperature.setFont(font)
        self.labelTemperature.setObjectName("labelTemperature")
        self.gridLayout_2.addWidget(self.labelTemperature, 2, 0, 1, 1)
        self.lcdNumberTemperature = QtWidgets.QLCDNumber(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumberTemperature.setFont(font)
        self.lcdNumberTemperature.setObjectName("lcdNumberTemperature")
        self.gridLayout_2.addWidget(self.lcdNumberTemperature, 2, 1, 1, 1)
        self.labelGust = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelGust.sizePolicy().hasHeightForWidth())
        self.labelGust.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelGust.setFont(font)
        self.labelGust.setObjectName("labelGust")
        self.gridLayout_2.addWidget(self.labelGust, 0, 0, 1, 1)
        self.lcdNumberGust = QtWidgets.QLCDNumber(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumberGust.sizePolicy().hasHeightForWidth())
        self.lcdNumberGust.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lcdNumberGust.setFont(font)
        self.lcdNumberGust.setObjectName("lcdNumberGust")
        self.gridLayout_2.addWidget(self.lcdNumberGust, 0, 1, 1, 1)
        self.lcdNumber_WindSpeed = QtWidgets.QLCDNumber(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber_WindSpeed.sizePolicy().hasHeightForWidth())
        self.lcdNumber_WindSpeed.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(14)
        font.setItalic(True)
        self.lcdNumber_WindSpeed.setFont(font)
        self.lcdNumber_WindSpeed.setObjectName("lcdNumber_WindSpeed")
        self.gridLayout_2.addWidget(self.lcdNumber_WindSpeed, 1, 1, 1, 1)
        self.labelGustBar = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelGustBar.sizePolicy().hasHeightForWidth())
        self.labelGustBar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelGustBar.setFont(font)
        self.labelGustBar.setFrameShape(QtWidgets.QFrame.Panel)
        self.labelGustBar.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelGustBar.setText("")
        self.labelGustBar.setObjectName("labelGustBar")
        self.gridLayout_2.addWidget(self.labelGustBar, 0, 2, 1, 1)
        self.labelSpeed = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelSpeed.setFont(font)
        self.labelSpeed.setObjectName("labelSpeed")
        self.gridLayout_2.addWidget(self.labelSpeed, 1, 0, 1, 1)
        self.labelSpeedBar = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelSpeedBar.setFont(font)
        self.labelSpeedBar.setFrameShape(QtWidgets.QFrame.Panel)
        self.labelSpeedBar.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelSpeedBar.setText("")
        self.labelSpeedBar.setObjectName("labelSpeedBar")
        self.gridLayout_2.addWidget(self.labelSpeedBar, 1, 2, 1, 1)
        self.labelTemperatureBar = QtWidgets.QLabel(self.layoutWidget)
        self.labelTemperatureBar.setMinimumSize(QtCore.QSize(800, 30))
        self.labelTemperatureBar.setObjectName("labelTemperatureBar")
        self.gridLayout_2.addWidget(self.labelTemperatureBar, 2, 2, 1, 1)
        self.labelRainfallBar = QtWidgets.QLabel(self.layoutWidget)
        self.labelRainfallBar.setObjectName("labelRainfallBar")
        self.gridLayout_2.addWidget(self.labelRainfallBar, 3, 2, 1, 1)
        self.labelError = QtWidgets.QLabel(self.centralwidget)
        self.labelError.setGeometry(QtCore.QRect(240, 850, 591, 20))
        self.labelError.setObjectName("labelError")
        self.progressBarQueue = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBarQueue.setGeometry(QtCore.QRect(280, 760, 141, 16))
        self.progressBarQueue.setMaximum(10)
        self.progressBarQueue.setProperty("value", 0)
        self.progressBarQueue.setTextVisible(False)
        self.progressBarQueue.setObjectName("progressBarQueue")
        self.labelMessageCounterTotal = QtWidgets.QLabel(self.centralwidget)
        self.labelMessageCounterTotal.setGeometry(QtCore.QRect(450, 720, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelMessageCounterTotal.setFont(font)
        self.labelMessageCounterTotal.setObjectName("labelMessageCounterTotal")
        self.canvasMatplot = canvasMatplot(self.centralwidget)
        self.canvasMatplot.setGeometry(QtCore.QRect(20, 340, 841, 371))
        self.canvasMatplot.setObjectName("canvasMatplot")
        self.radioButtonGraphDateAll = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonGraphDateAll.setGeometry(QtCore.QRect(20, 730, 98, 21))
        self.radioButtonGraphDateAll.setChecked(True)
        self.radioButtonGraphDateAll.setObjectName("radioButtonGraphDateAll")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButtonGraphDateAll)
        self.radioButtonGraphDateMonth = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonGraphDateMonth.setGeometry(QtCore.QRect(70, 730, 98, 21))
        self.radioButtonGraphDateMonth.setObjectName("radioButtonGraphDateMonth")
        self.buttonGroup.addButton(self.radioButtonGraphDateMonth)
        self.radioButtonGraphDateWeek = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonGraphDateWeek.setGeometry(QtCore.QRect(140, 730, 98, 21))
        self.radioButtonGraphDateWeek.setObjectName("radioButtonGraphDateWeek")
        self.buttonGroup.addButton(self.radioButtonGraphDateWeek)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1282, 22))
        self.menubar.setObjectName("menubar")
        self.menuRTL_Monitor = QtWidgets.QMenu(self.menubar)
        self.menuRTL_Monitor.setObjectName("menuRTL_Monitor")
        self.menuLogs = QtWidgets.QMenu(self.menubar)
        self.menuLogs.setObjectName("menuLogs")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuRTL_Monitor.menuAction())
        self.menubar.addAction(self.menuLogs.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RTL Monitor"))
        self.pushButton_Start.setText(_translate("MainWindow", "Start RTL"))
        self.pushButton_Quit.setText(_translate("MainWindow", "Stop RTL"))
        self.labelTime.setText(_translate("MainWindow", "00:00:00"))
        self.labelDirectionDeg.setText(_translate("MainWindow", "Degrees"))
        self.labelDirectionStr_2.setText(_translate("MainWindow", "Direction"))
        self.labelDirectionStr.setText(_translate("MainWindow", "---------"))
        self.labelMessageCounter.setText(_translate("MainWindow", "Message Queue"))
        self.labelGust_4.setText(_translate("MainWindow", "Gust"))
        self.labelRain.setText(_translate("MainWindow", "Rainfall"))
        self.labelTemperature.setText(_translate("MainWindow", "Temperature"))
        self.labelGust.setText(_translate("MainWindow", "Gust"))
        self.labelSpeed.setText(_translate("MainWindow", "Speed"))
        self.labelTemperatureBar.setText(_translate("MainWindow", "TextLabel"))
        self.labelRainfallBar.setText(_translate("MainWindow", "TextLabel"))
        self.labelError.setText(_translate("MainWindow", "Status"))
        self.labelMessageCounterTotal.setText(_translate("MainWindow", "Message Count"))
        self.radioButtonGraphDateAll.setText(_translate("MainWindow", "All"))
        self.radioButtonGraphDateMonth.setText(_translate("MainWindow", "Month"))
        self.radioButtonGraphDateWeek.setText(_translate("MainWindow", "Week"))
        self.menuRTL_Monitor.setTitle(_translate("MainWindow", "RTL Monitor"))
        self.menuLogs.setTitle(_translate("MainWindow", "Logs"))
from canvasmatplot import canvasMatplot
